version: '2'
services:
  web:
    build: .
    restart: always
    networks:
      - globalproxy_default
    volumes:
      - database:/usr/src/app/db.sqlite3
    restart: always
volumes:
  database:
    driver: local
networks:
  globalproxy_default:
    external: true
