version: '2'
services:
  web:
    build: .
    networks:
      - globalproxy_default
    volumes:
      - database:/usr/src/app/db
      - avatar:/usr/src/app/app/media/avatar
volumes:
  database:
    driver: local
  avatar:
    driver: local
networks:
  globalproxy_default:
    external: true
